name: Quizify Deployment
on: push
jobs:
  get_client_id:
    runs-on: ubuntu-latest
    steps:
      - name: GET_CLIENT_ID
        run: |
            echo "Got CLIENT_ID"
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
